FROM node:16

ARG USER_ID=500
ARG GROUP_ID=500

RUN groupadd -g ${GROUP_ID} nodeuser && \
    useradd -m -u ${USER_ID} -g ${GROUP_ID} nodeuser

RUN npm install -g webpack webpack-cli

USER nodeuser

WORKDIR /app

CMD ["npm", "start"]